# 9.6

다음 프로그램의 실행 결과를 보이시오

### (1)

```java
class Ex extends Exception{}
public class ExerciseCh9_6_1 {
    public static void main(String[] args){
        System.out.println("Entering first try block");
        try{
            System.out.println("Entering second try block");
            try{
                throw new Ex();
            }finally{
                System.out.println("finally in 2nd try block");
            }
        }catch (Ex e){
            System.out.println("Caught Ex in first try block");
        }finally{
            System.out.println("finally in 1st try block");
        }
    }
}
```

### (2)

```java
class FinallyClause{
    public int methodA(){
        try{
            return 1;
        }
        catch(Exception e){ return 2; }
    }

    public int methodB(){
        try{
            return 3;
        }
        finally {
            return 4;
        }
    }
}
public class ExerciseCh9_6_2 {
    public static void main(String[] args){
        FinallyClause fc = new FinallyClause();
        System.out.println("methodA returns "+ fc.methodA());
        System.out.println("methondB returns "+ fc.methodB());
    }
}
```

### (3)

```java
public class ExerciseCh9_6_3 {
    static void triangle_area(int w,int h){
        assert (w>0) : "width must be postive.";
        assert (h>0) : "height must be postive";

        //compute area
    }
    public static void main(String[] args){
        triangle_area(100,200);
        triangle_area(-10,5);
    }
}
```

### [**Solution**](../Solutions/9.6.md)

___

### [**Back to the List**](../#list-of-problems)
