# 1.5

다음 프로그램의 실행 결과를 쓰시오.

#### (1)
```c#
using System;
delegate void Delegate();
class ExerciseCh1_5_1 {
    public static void Method1(){
        Console.WriteLine("In the Method 1 ...");
    }
    public static void Method2(){
        Console.WriteLine("In the Method 2 ...");
    }
    public static void Main(){
        Delegate d = new Delegate(Method1);
        d += new Delegate(Method2);
        d();
    }
}
```

#### (2)

```c#
using System;
class ExerciseCh1_5_2 {
    public static void Main()
    {
        int i = 1, j = 0, k;
        try
        {
            Console.WriteLine("Exception checking...");
            k = i / j;
            Console.WriteLine("After Exception happening...");
        }
        catch (Exception e)
        {
            Console.WriteLine("Caught Exception...");
        }
        finally
        {
            Console.WriteLine("In the finally statement...");
        }
    }
}
```

#### (3)

```c#
using System;
class ExerciseCh1_5_3 {
    public static void Main(string[] args){
        foreach (string s in args)
            Console.WriteLine(s);
    }
}
```

### [**Solution**](../Solutions/1.5.md)

___

### [**Back to the List**](../#list-of-problems)